[package]
name = "boogie"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.1"
chumsky = { version = "1.0.0-alpha.7", git = "https://github.com/ojkelly/chumsky", branch = "patch-1", features = ["label", "pratt"] }
color-eyre = "0.6.3"
logos = "0.14.1"
regex = "1.10.6"
